### ISSUE TITLE
Cannot run the test example

### ISSUE THREAD

**Issue by peebles** [WolfgangFahl/pdfindexer#4]
I am running a docker container to try the example, openjdk:7.  Is that a good version?  But the example does not run:

```sh
$ docker run --rm -it -v $(pwd):/deploy -w /deploy openjdk:7 bash

root@cf534cbeea6a:/deploy# java -jar pdfindex.jar --sourceFileList test/pdffiles.lst --idxfile test/index2 --outputfile test/html/pdfindex.html --searchKeyWordList test/searchwords.txt --root test/
adding test/pdfsource1/LoremIpsum.pdf to index
Aug 12, 2018 1:10:33 AM org.apache.pdfbox.pdfparser.NonSequentialPDFParser checkXrefOffsets
SEVERE: Can't find the object 8 0 (origin offset 0)
creating output test/html/pdfindex.html
java.io.FileNotFoundException: test/html/pdfindex.html (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at java.io.PrintWriter.<init>(PrintWriter.java:263)
	at com.bitplan.pdfindex.Pdfindexer.getOutput(Pdfindexer.java:596)
	at com.bitplan.pdfindex.Pdfindexer.doIndex(Pdfindexer.java:669)
	at com.bitplan.pdfindex.Pdfindexer.work(Pdfindexer.java:693)
	at com.bitplan.pdfindex.Pdfindexer.maininstance(Pdfindexer.java:751)
	at com.bitplan.pdfindex.Pdfindexer.main(Pdfindexer.java:771)
test/html/pdfindex.html (No such file or directory)
```
I wanted to see the example run before I pursued trying this in my project.  Any suggestions?

**Comment by WolfgangFahl** [comment]
see http://wiki.bitplan.com/index.php/PdfIndexer#Trying_things_out - you might want to create the output folder before using it. Looks like git doesn't transfer the folder since it's gitignored and empty by default ... OpenJDK 7 should be fine for versions up to 0.0.10. From 0.0.11 on it will be Java8 ...
